#!/bin/sh
set -e

ENV_FILE=/var/www/html/femi9/billing/shared/.env

if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" <<EOF
DB_HOST=${DB_HOST:-db}
DB_PORT=${DB_PORT:-3306}
DB_USERNAME=${DB_USERNAME:-root}
DB_PASSWORD=${DB_PASSWORD:-root}
DB_NAME=${DB_NAME:-billing0femi9_billingapp}

ESPO_DB_HOST=${ESPO_DB_HOST:-}
ESPO_DB_PORT=${ESPO_DB_PORT:-3306}
ESPO_DB_USERNAME=${ESPO_DB_USERNAME:-}
ESPO_DB_PASSWORD=${ESPO_DB_PASSWORD:-}
ESPO_DB_NAME=${ESPO_DB_NAME:-}

WHATSAPP_BUSINESS_ID=${WHATSAPP_BUSINESS_ID:-}
WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID:-}
WHATSAPP_API_TOKEN=${WHATSAPP_API_TOKEN:-}
WHATSAPP_API_BASE=${WHATSAPP_API_BASE:-https://graph.facebook.com/v20.0}

ADMIN_EMAIL=${ADMIN_EMAIL:-}
APP_URL=${APP_URL:-http://localhost:8080}

GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY:-}
GOOGLE_GEOCODING_API_KEY=${GOOGLE_GEOCODING_API_KEY:-}

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}

ENCRYPTION_KEY=${ENCRYPTION_KEY:-docker-local-dev-placeholder-key-change-me}

INVOICE_SHARE_SIGNING_KEY=${INVOICE_SHARE_SIGNING_KEY:-}
EOF
    echo "Generated $ENV_FILE from container environment variables."
fi

exec "$@"
